#!/usr/bin/env python3
"""Builds the full directory dataset from the reference document and validates it."""
import json, re

# ─── TRADITIONS (hierarchical tree) ──────────────────────────────────────────
traditions = [
    # Universal
    {"id":"universal","parentId":None,"name":"Universal / Cross-Denominational","level":"branch",
     "description":"Resources used across all Orthodox communities.","primaryLanguages":["he","en"],"audioFirst":False},

    # Haredi branch
    {"id":"haredi","parentId":None,"name":"Haredi","level":"branch"},
    {"id":"hasidic","parentId":"haredi","name":"Hasidic","level":"stream"},
    {"id":"litvish","parentId":"haredi","name":"Litvish / Yeshivish","level":"stream",
     "description":"Non-Hasidic Lithuanian stream; intensive Talmud study rooted in the Vilna Gaon.","primaryLanguages":["en","he"],"audioFirst":False},

    # Hasidic dynasties
    {"id":"chabad","parentId":"hasidic","name":"Chabad-Lubavitch","level":"dynasty","primaryLanguages":["en","he"],"audioFirst":False},
    {"id":"breslov","parentId":"hasidic","name":"Breslov","level":"dynasty","primaryLanguages":["en","he"],"audioFirst":False},
    {"id":"ger","parentId":"hasidic","name":"Ger (Gur)","level":"dynasty","altNames":["Gur"],"primaryLanguages":["he","yi"],"audioFirst":False},
    {"id":"satmar","parentId":"hasidic","name":"Satmar","level":"dynasty","primaryLanguages":["yi"],"audioFirst":True,
     "notes":"Split between Kiryas Joel/Monroe (R. Aron Teitelbaum) and Williamsburg (R. Zalman Leib Teitelbaum) — verify before publishing."},
    {"id":"belz","parentId":"hasidic","name":"Belz","level":"dynasty","primaryLanguages":["yi","he"],"audioFirst":True},
    {"id":"vizhnitz","parentId":"hasidic","name":"Vizhnitz","level":"dynasty","altNames":["Viznitz"],"primaryLanguages":["yi","he"],"audioFirst":True},
    {"id":"bobov","parentId":"hasidic","name":"Bobov","level":"dynasty","primaryLanguages":["yi","he"],"audioFirst":True},
    {"id":"skver","parentId":"hasidic","name":"Skver","level":"dynasty","altNames":["Skvyra"],"primaryLanguages":["yi","he"],"audioFirst":True},
    {"id":"munkatch","parentId":"hasidic","name":"Munkatch","level":"dynasty","altNames":["Munkacs","Munkács","Minkatch"],"primaryLanguages":["yi","he"],"audioFirst":True,"notes":"Hungarian anti-Zionist dynasty (~2,500 families); associated with the Minchas Elazar."},

    # Modern Orthodox
    {"id":"modern-orthodox","parentId":None,"name":"Modern Orthodox","level":"branch","primaryLanguages":["en","he"],"audioFirst":False},

    # Sephardic / Mizrahi
    {"id":"sephardic","parentId":None,"name":"Sephardic / Mizrahi","level":"branch",
     "description":"Several distinct rites, not one bloc.","primaryLanguages":["he","en"],"audioFirst":False},
    {"id":"sephardic-ovadia","parentId":"sephardic","name":"Rav Ovadia mainstream","level":"rite","primaryLanguages":["he"],"audioFirst":False},
    {"id":"sephardic-syrian","parentId":"sephardic","name":"Syrian / Aleppo (Halab)","level":"rite","primaryLanguages":["en","he"],"audioFirst":False},
    {"id":"sephardic-iraqi","parentId":"sephardic","name":"Iraqi / Baghdadi","level":"rite","primaryLanguages":["he"],"audioFirst":False},
    {"id":"sephardic-moroccan","parentId":"sephardic","name":"Moroccan / North African","level":"rite","altNames":["Maghrebi"],"primaryLanguages":["he","fr"],"audioFirst":False},
    {"id":"sephardic-yemenite","parentId":"sephardic","name":"Yemenite (Teimani)","level":"rite","altNames":["Baladi","Shami","Dor Daim"],"primaryLanguages":["he"],"audioFirst":False},
    {"id":"sephardic-spanish-portuguese","parentId":"sephardic","name":"Spanish & Portuguese","level":"rite","altNames":["Western Sephardim","S&P"],"primaryLanguages":["en","he"],"audioFirst":False},
    {"id":"bnei-anusim","parentId":"sephardic","name":"Bnei Anusim","level":"community","altNames":["Anusim","Crypto-Jews","Conversos","Marranos","B'nai Anusim"],"primaryLanguages":["es","pt"],"audioFirst":False,"notes":"Descendants of Sephardic/Portuguese Jews forcibly converted during the Inquisition who are reconnecting with Judaism. A community defined by history and return, not a distinct rite; returnees generally adopt mainstream Sephardic practice."},

    # Beta Israel
    {"id":"beta-israel","parentId":None,"name":"Beta Israel (Ethiopian)","level":"community","altNames":["Ethiopian Jewry"],
     "description":"Non-rabbinic Haymanot tradition, oral and in Ge'ez. Most adherents in Israel now practice Sephardic-style rabbinic Orthodoxy.",
     "primaryLanguages":["gez","he"],"audioFirst":False,
     "notes":"Heritage material lives in academic archives, not study platforms; build with community input."},
    {"id":"bnei-menashe","parentId":None,"name":"Bnei Menashe","level":"community","altNames":["Children of Manasseh","Shinlung","Bene Menashe","B'nei Menashe"],
     "description":"Community from Mizoram and Manipur in northeast India (Chin/Kuki/Mizo ethnic groups) who claim descent from the lost tribe of Manasseh and have adopted Judaism. ~10,000 members; ~5,000 have made aliyah, the rest awaiting it.",
     "primaryLanguages":["en","he"],"audioFirst":False,
     "notes":"Emerging/returning community, not a classical rite. Recognized as a 'lost tribe' group by a 2005 Israeli Chief Rabbi ruling, but members undergo formal Orthodox conversion on arrival; halachic and historical status are debated. Present as community + supporting organizations, not a status ruling."},
]

# ─── AUTHORITIES (people) ────────────────────────────────────────────────────
authorities = [
    {"id":"ovadia-yosef","name":"Rav Ovadia Yosef","role":["posek","author"],"traditionIds":["sephardic-ovadia"],"lifespan":"1920-2013"},
    {"id":"yitzchak-yosef","name":"Rabbi Yitzchak Yosef","role":["posek","author"],"traditionIds":["sephardic-ovadia"],"lifespan":"b. 1952","notes":"Author of Yalkut Yosef; son of Rav Ovadia; former Rishon LeZion."},
    {"id":"yosef-chaim-baghdad","name":"Rabbi Yosef Chaim of Baghdad","altNames":["Ben Ish Chai"],"role":["posek","author"],"traditionIds":["sephardic-iraqi","sephardic"],"lifespan":"1835-1909"},
    {"id":"yaakov-chaim-sofer","name":"Rabbi Yaakov Chaim Sofer","altNames":["Kaf HaChaim"],"role":["posek","author"],"traditionIds":["sephardic-iraqi"],"lifespan":"1870-1939"},
    {"id":"shalom-messas","name":"Rabbi Shalom Messas","role":["posek","author"],"traditionIds":["sephardic-moroccan"],"lifespan":"1909-2003","notes":"Chief Sephardic rabbi of Jerusalem; leading 20th-c. Moroccan posek."},
    {"id":"mordechai-lebhar","name":"Rabbi Mordechai Lebhar","altNames":["Magen Avot"],"role":["posek","author","maggid-shiur"],"traditionIds":["sephardic-moroccan"],"notes":"Author of Magen Avot; emerging leader in the Moroccan rabbinate (Montreal/LA)."},
    {"id":"yaakov-menashe","name":"Rabbi Yaakov Menashe","role":["maggid-shiur","author"],"traditionIds":["sephardic-iraqi"],"notes":"Founder of Midrash Ben Ish Hai / A Torah Minute; serves the Baghdadi diaspora."},
    {"id":"david-yosef","name":"Rabbi David Yosef","altNames":["Halacha Brura"],"role":["posek","author"],"traditionIds":["sephardic-ovadia"],"lifespan":"b. 1957","notes":"Son of Rav Ovadia; author of Halacha Brura; member of the Council of Torah Sages."},
    {"id":"eli-mansour","name":"Rabbi Eli J. Mansour","role":["maggid-shiur","author"],"traditionIds":["sephardic-syrian"],"lifespan":"b. 1968"},
    {"id":"yosef-qafih","name":"Rabbi Yosef Qafih","altNames":["Kapach"],"role":["posek","author"],"traditionIds":["sephardic-yemenite"],"lifespan":"1917-2000"},
    {"id":"chofetz-chaim","name":"Rabbi Yisrael Meir Kagan","altNames":["Chofetz Chaim"],"role":["posek","author"],"traditionIds":["litvish"],"lifespan":"1838-1933"},
    {"id":"moshe-feinstein","name":"Rabbi Moshe Feinstein","altNames":["Igros Moshe"],"role":["posek","author"],"traditionIds":["litvish"],"lifespan":"1895-1986"},
    {"id":"yitzchak-hutner","name":"Rabbi Yitzchak Hutner","altNames":["Pachad Yitzchak"],"role":["rosh-yeshiva","author"],"traditionIds":["litvish"],"lifespan":"1906-1980"},
    {"id":"shraga-feivel-mendlowitz","name":"Rabbi Shraga Feivel Mendlowitz","role":["founder","rosh-yeshiva"],"traditionIds":["litvish"],"lifespan":"1886-1948"},
    {"id":"nachman-breslov","name":"Rebbe Nachman of Breslov","role":["rebbe","author"],"traditionIds":["breslov"],"lifespan":"1772-1810"},
    {"id":"nasan-maimon","name":"Rabbi Nasan Maimon","role":["maggid-shiur","founder"],"traditionIds":["breslov"]},
    {"id":"yehuda-aryeh-leib-alter","name":"Rabbi Yehudah Aryeh Leib Alter","altNames":["Sfas Emes"],"role":["rebbe","author"],"traditionIds":["ger"],"lifespan":"1847-1905"},
    {"id":"yitzchak-meir-alter","name":"Rabbi Yitzchak Meir Alter","altNames":["Chiddushei HaRim"],"role":["rebbe","founder","author"],"traditionIds":["ger"],"lifespan":"1798-1866"},
    {"id":"yaakov-aryeh-alter","name":"Rabbi Yaakov Aryeh Alter","role":["rebbe"],"traditionIds":["ger"],"lifespan":"b. 1939","notes":"Current Gerrer Rebbe."},
    {"id":"yoel-teitelbaum","name":"Rabbi Yoel Teitelbaum","altNames":["Vayoel Moshe","Satmar Rav"],"role":["rebbe","founder","author"],"traditionIds":["satmar"],"lifespan":"1887-1979"},
    {"id":"yissachar-dov-rokeach","name":"Rabbi Yissachar Dov Rokeach","role":["rebbe"],"traditionIds":["belz"],"lifespan":"b. 1948","notes":"Current Belzer Rebbe."},
    {"id":"chaim-meir-hager","name":"Rabbi Chaim Meir Hager","altNames":["Imrei Chaim"],"role":["rebbe","author"],"traditionIds":["vizhnitz"],"lifespan":"1887-1972"},
    {"id":"benzion-halberstam","name":"Rabbi Benzion Halberstam","altNames":["Kedushas Tzion"],"role":["rebbe","author"],"traditionIds":["bobov"],"lifespan":"1874-1941"},
    {"id":"david-twersky","name":"Rabbi David Twersky","role":["rebbe"],"traditionIds":["skver"],"lifespan":"b. 1940","notes":"Current Skverer Rebbe of New Square."},
    {"id":"chaim-elazar-spira","name":"Rabbi Chaim Elazar Spira","altNames":["Minchas Elazar"],"role":["rebbe","posek","author"],"traditionIds":["munkatch"],"lifespan":"1868-1937","notes":"Munkatcher Rebbe; prominent anti-Zionist posek."},
    {"id":"menachem-mendel-schneerson","name":"Rabbi Menachem Mendel Schneerson","altNames":["The Lubavitcher Rebbe"],"role":["rebbe","author"],"traditionIds":["chabad"],"lifespan":"1902-1994"},
    {"id":"hershel-schachter","name":"Rabbi Hershel Schachter","role":["rosh-yeshiva","posek"],"traditionIds":["modern-orthodox"],"lifespan":"b. 1941"},
    {"id":"david-fohrman","name":"Rabbi David Fohrman","role":["author","maggid-shiur"],"traditionIds":["modern-orthodox"]},
    {"id":"jonathan-sacks","name":"Rabbi Lord Jonathan Sacks","altNames":["Covenant & Conversation"],"role":["author","posek"],"traditionIds":["modern-orthodox"],"lifespan":"1948-2020","notes":"Chief Rabbi of the UK (1991-2013); philosopher and author."},
    {"id":"tovia-singer","name":"Rabbi Tovia Singer","role":["founder","author","maggid-shiur"],"traditionIds":["universal"],"lifespan":"b. 1960","notes":"Founder/director of Outreach Judaism; counter-missionary educator; author of 'Let's Get Biblical'."},
    {"id":"bentzion-kravitz","name":"Rabbi Bentzion Kravitz","role":["founder","author"],"traditionIds":["universal"],"notes":"Founder of Jews for Judaism (1985); counter-missionary educator and counselor."},
    {"id":"chaim-brovender","name":"Rabbi Chaim Brovender","role":["founder","rosh-yeshiva"],"traditionIds":["modern-orthodox"]},
    {"id":"adin-steinsaltz","name":"Rabbi Adin Even-Israel Steinsaltz","role":["author"],"traditionIds":["modern-orthodox"],"lifespan":"1937-2020"},
    {"id":"michelle-farber","name":"Rabbanit Michelle Cohen Farber","role":["maggid-shiur","founder"],"traditionIds":["modern-orthodox"]},
    {"id":"eli-stefansky","name":"Rabbi Eli Stefansky","role":["maggid-shiur"],"traditionIds":["litvish"]},
]

# ─── TEXTS (canonical works) ─────────────────────────────────────────────────
texts = [
    {"id":"mishnah-berurah","title":"Mishnah Berurah","category":"halacha","authorId":"chofetz-chaim","traditionIds":["litvish"],"onSefaria":True,"onHebrewbooks":True,"notes":"Primary halachic reference for Litvish Ashkenazim."},
    {"id":"igros-moshe","title":"Igros Moshe","category":"responsa","authorId":"moshe-feinstein","traditionIds":["litvish"],"onSefaria":True,"onHebrewbooks":True},
    {"id":"pachad-yitzchak","title":"Pachad Yitzchak","category":"mussar","authorId":"yitzchak-hutner","traditionIds":["litvish"],"onSefaria":False,"onHebrewbooks":True},
    {"id":"ben-ish-chai","title":"Ben Ish Chai","transliteration":"Ben Ish Ḥai","category":"halacha","authorId":"yosef-chaim-baghdad","traditionIds":["sephardic-iraqi","sephardic"],"onSefaria":True,"onHebrewbooks":True,"notes":"Functions as a Sephardic/Mizrahi Kitzur Shulchan Aruch."},
    {"id":"kaf-hachaim","title":"Kaf HaChaim","category":"halacha","authorId":"yaakov-chaim-sofer","traditionIds":["sephardic-iraqi"],"onSefaria":True,"onHebrewbooks":True},
    {"id":"magen-avot","title":"Magen Avot","category":"halacha","authorId":"mordechai-lebhar","traditionIds":["sephardic-moroccan"],"onSefaria":False,"onHebrewbooks":False,"notes":"Authoritative work on Moroccan laws and customs (Orach Hayim, Yoreh Deah, Even HaEzer)."},
    {"id":"darke-abotenou","title":"Darké Abotenou","category":"halacha","authorId":"mordechai-lebhar","traditionIds":["sephardic-moroccan"],"onSefaria":False,"onHebrewbooks":False,"notes":"English work on Moroccan laws and customs, based on Magen Avot."},
    {"id":"yabia-omer","title":"Yabia Omer","category":"responsa","authorId":"ovadia-yosef","traditionIds":["sephardic-ovadia"],"onSefaria":True,"onHebrewbooks":True},
    {"id":"yalkut-yosef","title":"Yalkut Yosef","category":"halacha","authorId":"yitzchak-yosef","traditionIds":["sephardic-ovadia"],"onSefaria":False,"onHebrewbooks":True,"notes":"Saka Edition is the English print edition."},
    {"id":"sfas-emes","title":"Sfas Emes","transliteration":"Sefat Emet","category":"chassidus","authorId":"yehuda-aryeh-leib-alter","traditionIds":["ger"],"onSefaria":True,"onHebrewbooks":True},
    {"id":"chiddushei-harim","title":"Chiddushei HaRim","category":"chassidus","authorId":"yitzchak-meir-alter","traditionIds":["ger"],"onSefaria":True,"onHebrewbooks":True},
    {"id":"likutey-moharan","title":"Likutey Moharan","category":"chassidus","authorId":"nachman-breslov","traditionIds":["breslov"],"onSefaria":True,"onHebrewbooks":True},
    {"id":"vayoel-moshe","title":"Vayoel Moshe","category":"other","authorId":"yoel-teitelbaum","traditionIds":["satmar"],"onSefaria":False,"onHebrewbooks":True},
    {"id":"divrei-yoel","title":"Divrei Yoel","category":"responsa","authorId":"yoel-teitelbaum","traditionIds":["satmar"],"onSefaria":False,"onHebrewbooks":True},
    {"id":"imrei-chaim","title":"Imrei Chaim","category":"chassidus","authorId":"chaim-meir-hager","traditionIds":["vizhnitz"],"onSefaria":False,"onHebrewbooks":True},
    {"id":"kedushas-tzion","title":"Kedushas Tzion","category":"chassidus","authorId":"benzion-halberstam","traditionIds":["bobov"],"onSefaria":False,"onHebrewbooks":True},
    {"id":"minchas-elazar","title":"Minchas Elazar","category":"responsa","authorId":"chaim-elazar-spira","traditionIds":["munkatch"],"onSefaria":False,"onHebrewbooks":True,"notes":"Four volumes of responsa (fifth posthumous, 1974)."},
    {"id":"tanya","title":"Tanya","category":"chassidus","authorId":None,"traditionIds":["chabad"],"onSefaria":True,"onHebrewbooks":True,"notes":"Foundational Chabad text (R. Schneur Zalman of Liadi)."},
    {"id":"orit","title":"Orit","category":"tanakh","authorId":None,"traditionIds":["beta-israel"],"onSefaria":False,"onHebrewbooks":False,"notes":"Ge'ez Octateuch (Torah + Joshua, Judges, Ruth); core Beta Israel canon."},
    {"id":"teezaza-sanbat","title":"Te'ezaza Sanbat","category":"halacha","authorId":None,"traditionIds":["beta-israel"],"onSefaria":False,"onHebrewbooks":False,"notes":"'Commandments of the Sabbath'; influenced by Jubilees."},
]

# ─── RESOURCES ───────────────────────────────────────────────────────────────
V = lambda s, d=None, n=None: {k:v for k,v in {"status":s,"lastChecked":d,"note":n}.items() if v is not None}
LIVE = "2026-06-02"

resources = [
    # I. Universal
    {"id":"sefaria","name":"Sefaria","type":"text-library","url":"https://www.sefaria.org","description":"Free, open-access library of Jewish texts in Hebrew and English with a public API (v3 Texts, Linker). The directory's primary text backbone.","traditionIds":["universal"],"languages":["he","en"],"medium":["text"],"access":"api-open","hasApi":True,"verification":V("verified-live",LIVE)},
    {"id":"hebrewbooks","name":"HebrewBooks.org","type":"text-library","url":"https://www.hebrewbooks.org","description":"Scanned archive of 50,000+ sefarim, many OCR-searchable; invaluable for rare or older texts.","traditionIds":["universal"],"languages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"daat","name":"Daat","type":"text-library","url":"https://www.daat.ac.il","description":"Israeli library maintained by Herzog College; extensive Hebrew-text repository across history, philosophy, and halacha.","traditionIds":["universal"],"languages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"alhatorah","name":"AlHaTorah.org","type":"text-library","url":"https://www.alhatorah.org","description":"2,500 years of Biblical commentary; Mikraot Gedolot, Daf Yomi tools, Mishneh Torah.","traditionIds":["universal"],"languages":["he","en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"torahanytime","name":"TorahAnytime","type":"shiur-library","url":"https://www.torahanytime.com","description":"Largest library of recorded Torah videos (70,000+ shiurim from 1,000+ speakers). Cross-denominational.","traditionIds":["universal"],"languages":["en","he"],"medium":["video","audio"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"alltorah","name":"AllTorah.org","type":"general-portal","url":"https://www.alltorah.org","description":"Curated collection of free Torah apps/websites; includes All Daf, All Parsha, All Mishnah, All Halachah.","traditionIds":["universal"],"languages":["en"],"medium":["text","audio","video"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},

    # II. Hasidic — Chabad
    {"id":"chabad-org","name":"Chabad.org","type":"general-portal","url":"https://www.chabad.org","description":"The most extensive Hasidic web presence; full Tanakh with Rashi, daily study, Tanya/Chassidus library, Kehot corpus.","traditionIds":["chabad","universal"],"languages":["en","he"],"medium":["text","audio","video"],"textIds":["tanya"],"authorityIds":["menachem-mendel-schneerson"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"jnet","name":"JNet / Jewish Learning Network","type":"organization","url":"https://www.jnet.org","description":"Chabad's adult education arm under Merkos L'Inyonei Chinuch; pairs learners with study partners.","traditionIds":["chabad"],"languages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"kabbalahonline","name":"KabbalahOnline.org","type":"text-library","url":"https://www.chabad.org/kabbalah","description":"Kabbalistic and Chassidic teachings from the Rebbe and earlier Chabad masters (via Chabad).","traditionIds":["chabad"],"languages":["en","he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"therebbe","name":"TheRebbe.org","type":"general-portal","url":"https://www.therebbe.org","description":"Dedicated to the teachings and life of the Lubavitcher Rebbe.","traditionIds":["chabad"],"languages":["en"],"medium":["text","video"],"authorityIds":["menachem-mendel-schneerson"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"sie","name":"Sichos in English","type":"text-library","url":"https://www.sie.org","description":"Extensive Chabad-Lubavitch sichot (talks) archive; useful for Hasidic thought broadly.","traditionIds":["chabad","hasidic"],"languages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},

    # II. Hasidic — Breslov
    {"id":"breslovtorah","name":"BreslovTorah.com","type":"text-library","url":"https://www.breslovtorah.com","description":"Resource center for students of Rebbe Nachman; founded by R. Nasan Maimon. Likutey Moharan, Likutey Halakhot, Reb Noson's writings.","traditionIds":["breslov"],"languages":["he","en"],"medium":["text","audio"],"textIds":["likutey-moharan"],"authorityIds":["nachman-breslov","nasan-maimon"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"breslov-research","name":"Breslov Research Institute","type":"publisher","url":"https://www.breslov.org","description":"Publisher of English translations of all of Rebbe Nachman's and Reb Noson's works; first to translate the full Breslov canon (est. 1979).","traditionIds":["breslov"],"languages":["en","he"],"medium":["print","text"],"textIds":["likutey-moharan"],"authorityIds":["nachman-breslov"],"access":"paid","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"nanach","name":"Na Nach","type":"organization","url":"https://www.nanach.org","altUrls":["https://nanachnation.org"],"description":"Resource affiliated with the Na Nach Nachma Nachman branch of Breslov; freely distributed teachings.","traditionIds":["breslov"],"languages":["he","en"],"medium":["text","audio"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},

    # II. Hasidic — Ger
    {"id":"sfasemes-org","name":"Torah of the Sfas Emes","type":"text-library","url":"https://sfasemes.org","description":"English-language discourses and study material on the Sfas Emes; closest thing Ger has to a dedicated English presence.","traditionIds":["ger"],"languages":["en","he"],"medium":["text"],"textIds":["sfas-emes"],"authorityIds":["yehuda-aryeh-leib-alter"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"torah-org-sfasemes","name":"Torah.org — Sfas Emes series","type":"text-library","url":"https://torah.org/series/sfas-emes/","description":"Dr. Nosson Chayim Leff's English presentations of a Sfas Emes ma'amar per parsha, with Hebrew alongside.","traditionIds":["ger"],"languages":["en","he"],"medium":["text"],"textIds":["sfas-emes"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # II. Hasidic — Satmar
    {"id":"torahjews-org","name":"Torah Jews (Natruna)","type":"organization","url":"https://torahjews.org","altUrls":["https://www.truetorahjews.org"],"description":"English window into Satmar / anti-Zionist hashkafa with curated Divrei Yoel and Vayoel Moshe excerpts.","traditionIds":["satmar"],"languages":["en"],"medium":["text"],"textIds":["vayoel-moshe","divrei-yoel"],"authorityIds":["yoel-teitelbaum"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"Prefer torahjews.org; truetorahjews.org is an older build with server errors.")},

    # II. Hasidic — Belz
    {"id":"worldofbelz","name":"World of Belz","type":"institution","url":"https://worldofbelz.org","description":"Official English-facing Belz institutions site; Torah content, a 24/6 TV channel, and outreach.","traditionIds":["belz"],"languages":["en","yi"],"medium":["text","video"],"authorityIds":["yissachar-dov-rokeach"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # II. Hasidic — Satmar (community site) + Munkatch
    {"id":"mysatmar","name":"My Satmar","type":"general-portal","url":"https://www.mysatmar.com","description":"Privately-run, unaffiliated Satmar community site: news archives, documents, and community media. Explicitly not an official Satmar institution.","traditionIds":["satmar"],"languages":["yi","en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"Live; self-described as privately owned, not affiliated with any Satmar community."),"flags":["Unofficial/privately operated."]},
    {"id":"minkatch-oitzar","name":"Oitzar HaSeforim — Minkatch (אוצר ספרי מונקאטש)","type":"text-library","url":"https://www.minkatch.org/oitzar","altUrls":["https://www.minkatch.org"],"description":"Library of all Munkatcher sefarim, presented by Hoitzuas Emes (Or Torah Munkatch), the dynasty's publishing institute in Borough Park.","traditionIds":["munkatch"],"languages":["he"],"uiLanguages":["he","yi"],"medium":["text"],"textIds":["minchas-elazar"],"authorityIds":["chaim-elazar-spira"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # II. Hasidic — cross-dynasty / Yiddish media
    {"id":"yiddish24","name":"Yiddish24 / Kol Mevaser","type":"hotline","url":"https://www.yiddish24.com","phone":"+1-212-444-1100","description":"Yiddish news-and-content hotline + app (est. 2005), ~100,000 daily listeners; dominant audio channel for the Yiddish-first dynasties.","traditionIds":["satmar","belz","vizhnitz","skver","hasidic"],"languages":["yi"],"medium":["audio","phone"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"torahdownloads","name":"TorahDownloads","type":"shiur-library","url":"https://www.torahdownloads.com","description":"Large free searchable library of recorded mp3 shiurim across Haredi speakers, Hasidic and Yeshivish.","traditionIds":["hasidic","litvish"],"languages":["en","yi"],"medium":["audio"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"heichal-hanegina","name":"Heichal HaNegina","type":"archive","url":"https://heichalhanegina.blogspot.com","description":"Hasidic music and story archive (blog). Site remains online but is dormant — no new posts since 2014.","traditionIds":["hasidic"],"languages":["en"],"medium":["text","audio"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"URL resolves but the blog is inactive (last post 2014)."),"flags":["Dormant — no posts since 2014; archival value only."]},

    # III. Litvish — institutions
    {"id":"bmg","name":"Beth Medrash Govoha (Lakewood)","type":"institution","url":"https://www.bmg.edu","description":"Largest yeshiva outside Israel (~9,600 students); spiritual center of American Litvish life. Limited public content.","traditionIds":["litvish"],"languages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"torah-vodaas","name":"Yeshiva Torah Vodaas","type":"institution","url":"https://www.torahvodaath.org","description":"Historic Brooklyn yeshiva (R. Shraga Feivel Mendlowitz); one of the first major American Litvish institutions.","traditionIds":["litvish"],"languages":["en"],"medium":["text"],"authorityIds":["shraga-feivel-mendlowitz"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"chaim-berlin","name":"Yeshiva Rabbi Chaim Berlin","type":"institution","url":"https://www.rabbinicalacademyrabbichaimberlin.org","description":"Founded 1904, oldest yeshiva in Brooklyn; shaped by R. Yitzchak Hutner. Limited public text presence.","traditionIds":["litvish"],"languages":["en"],"medium":["text"],"authorityIds":["yitzchak-hutner"],"textIds":["pachad-yitzchak"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"mir-brooklyn","name":"Mir Yeshiva (Brooklyn)","type":"institution","url":"https://www.mirmesivta.com","description":"American arm of the Mirrer Yeshiva; limited public-facing content.","traditionIds":["litvish"],"languages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},

    # III. Litvish — organizations
    {"id":"agudah","name":"Agudath Israel of America","type":"organization","url":"https://www.agudah.org","description":"Main Haredi umbrella organization in the US (Litvish + Hasidic); associated with the Moetzes Gedolei HaTorah.","traditionIds":["litvish","hasidic","haredi"],"languages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"dirshu","name":"Dirshu","type":"organization","url":"https://www.dirshu.com","description":"International Torah organization with accountability-based, test-driven learning (Daf HaYomi B'Halacha, Amud HaYomi, Kinyan Torah).","traditionIds":["litvish"],"languages":["he","en"],"medium":["text"],"textIds":["mishnah-berurah"],"access":"freemium","hasApi":False,"verification":V("verified-live","2026-06-02")},

    # III. Litvish — publisher + Daf Yomi platforms
    {"id":"artscroll","name":"ArtScroll / Mesorah","type":"publisher","url":"https://www.artscroll.com","description":"Dominant English publisher for the Yeshivish world; Schottenstein Talmud, Stone Chumash. Translations are copyrighted.","traditionIds":["litvish","universal"],"languages":["en","he"],"medium":["print","text"],"access":"copyright-restricted","hasApi":False,"verification":V("verified-live","2026-06-02"),"flags":["Translations cannot be rehosted; link only."]},
    {"id":"alldaf","name":"All Daf","type":"daily-study","url":"https://alldaf.org","description":"OU-run Daf Yomi app/site; thousands of daily-page shiurim, integrates Sefaria.","traditionIds":["litvish","modern-orthodox","universal"],"languages":["en"],"medium":["audio","video","text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"mdy","name":"Mercaz Daf Yomi (MDY)","type":"daily-study","url":"https://mdydafyomi.com","altUrls":["https://mercazdafyomi.com","https://mdydaf.com"],"description":"R. Eli Stefansky's MDY; one of the most-watched Daf Yomi shiurim worldwide (30,000+ members), video-first.","traditionIds":["litvish"],"languages":["en"],"medium":["video","audio"],"authorityIds":["eli-stefansky"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"Primary domain is mdydafyomi.com.")},
    {"id":"steinsaltz","name":"Steinsaltz / Aleph Society","type":"text-library","url":"https://steinsaltz.org","altUrls":["https://steinsaltz-center.org"],"description":"Free Daf Yomi material, a Daily Study app, and a full Talmud library; underlies the Koren Talmud Bavli.","traditionIds":["modern-orthodox","universal"],"languages":["en","he"],"medium":["text","audio"],"authorityIds":["adin-steinsaltz"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"hadran","name":"Hadran","type":"daily-study","url":"https://hadran.org.il","description":"Daf Yomi support and shiurim; founded by Rabbanit Michelle Farber (2018), notable for serving women learners.","traditionIds":["modern-orthodox","universal"],"languages":["en","he"],"medium":["audio","video","text"],"authorityIds":["michelle-farber"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"koveah","name":"Koveah","type":"app","url":"https://koveah.org","description":"Sefaria-powered tool (YU CJF / YUTorah) for building personalized learning schedules with daily reminders.","traditionIds":["modern-orthodox","universal"],"languages":["en","he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # IV. Modern Orthodox
    {"id":"yutorah","name":"YUTorah Online","type":"shiur-library","url":"https://www.yutorah.org","description":"240,000+ shiurim from Yeshiva University's RIETS and affiliated rabbis; largest Modern Orthodox content platform.","traditionIds":["modern-orthodox"],"languages":["en","he"],"medium":["audio","video","text"],"authorityIds":["hershel-schachter"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"ou-torah","name":"OU Torah / Orthodox Union","type":"general-portal","url":"https://outorah.org","altUrls":["https://www.ou.org/torah/"],"description":"Content arm of the Orthodox Union; parsha essays, halacha, holidays. Cross-denominational in tone.","traditionIds":["modern-orthodox","universal"],"languages":["en"],"medium":["text","audio"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"vbm","name":"VBM — Virtual Beit Midrash (Har Etzion)","type":"shiur-library","url":"https://www.etzion.org.il/en","description":"Sophisticated Modern Orthodox / Religious Zionist resource; pioneered the 'Tanakh methodology'. Gold standard for serious MO learning.","traditionIds":["modern-orthodox"],"languages":["en","he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"torahweb","name":"TorahWeb","type":"text-library","url":"https://www.torahweb.org","description":"Weekly parasha essays by prominent YU roshei yeshiva.","traditionIds":["modern-orthodox"],"languages":["en"],"medium":["text"],"authorityIds":["hershel-schachter"],"access":"free","hasApi":False,"verification":V("not-checked")},
    {"id":"mizrachi","name":"Mizrachi","type":"organization","url":"https://www.mizrachi.org","description":"Religious Zionist organization; strong Aliyah and Zionist Torah content within an Orthodox framework.","traditionIds":["modern-orthodox"],"languages":["en","he"],"medium":["text","video"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"rca","name":"Rabbinical Council of America (RCA)","type":"organization","url":"https://www.rabbis.org","description":"Main Modern Orthodox rabbinical body in the US; affiliated with the OU.","traditionIds":["modern-orthodox"],"languages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"webyeshiva","name":"WebYeshiva","type":"institution","url":"https://www.webyeshiva.org","description":"Live interactive online yeshiva/midrasha; founded by R. Chaim Brovender. Courses through Semicha level.","traditionIds":["modern-orthodox"],"languages":["en"],"medium":["video","text"],"authorityIds":["chaim-brovender"],"access":"freemium","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"alephbeta","name":"AlephBeta","type":"shiur-library","url":"https://www.alephbeta.org","description":"Animated Torah videos focusing on close reading; founded by R. David Fohrman. Accessible/educational tone.","traditionIds":["modern-orthodox"],"languages":["en"],"medium":["video"],"authorityIds":["david-fohrman"],"access":"freemium","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"aish","name":"Aish HaTorah","type":"organization","url":"https://www.aish.com","description":"Orthodox outreach organization; broad appeal across Modern Orthodox and Baal Teshuva communities.","traditionIds":["modern-orthodox","universal"],"languages":["en"],"medium":["text","video"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"koren","name":"Koren Publishers Jerusalem","type":"publisher","url":"https://www.korenpub.com","description":"MO-aligned publisher (founded 1962); Koren-Steinsaltz Talmud, Koren siddurim, Tanakh, Maggid Books. Main alternative to ArtScroll.","traditionIds":["modern-orthodox","universal"],"languages":["en","he"],"medium":["print"],"authorityIds":["adin-steinsaltz"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"rabbisacks","name":"The Rabbi Sacks Legacy","type":"archive","url":"https://rabbisacks.org","description":"Digital archive of Rabbi Lord Jonathan Sacks (UK Chief Rabbi 1991-2013): Covenant & Conversation parsha essays, books, videos, and teachings on Torah, ethics, and leadership.","traditionIds":["modern-orthodox"],"languages":["en"],"uiLanguages":["en"],"medium":["text","video"],"authorityIds":["jonathan-sacks"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"nleresources","name":"NLE Resources (Ner LeElef)","type":"general-portal","url":"https://nleresources.com","description":"Resource hub for Jewish educators and kiruv/outreach professionals (a project of Ner LeElef): the Morasha Syllabus, Thinking Gemara series, source sheets, and teaching materials.","traditionIds":["modern-orthodox","universal"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # IV-b. Judaica / Torah publishers
    {"id":"feldheim","name":"Feldheim Publishers","type":"publisher","url":"https://feldheim.com","description":"Major American Orthodox publisher (founded 1939, 'Torah Literature of Quality'): Jewish law, Torah, Talmud, holidays, biography, and kosher cookbooks.","traditionIds":["litvish","universal"],"languages":["en","he"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"menucha","name":"Menucha Publishers","type":"publisher","url":"https://menuchapublishers.com","description":"Brooklyn Orthodox English-language publisher (est. 2008/2011); originally Targum Press's US distributor. Torah, Jewish literature, children's books, cookbooks.","traditionIds":["litvish","universal"],"languages":["en"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"targum","name":"Targum Press","type":"publisher","url":"https://www.targumpublishers.com","description":"Orthodox English-language publisher (founded 1984); now associated with KTAV as an imprint. Torah, halacha, and popular Jewish works.","traditionIds":["litvish","universal"],"languages":["en"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE,"Targum is now run as an imprint of KTAV (ktav.com/collections/targum).")},
    {"id":"ktav","name":"KTAV Publishing House","type":"publisher","url":"https://ktav.com","description":"Long-established Brooklyn Judaica publisher (founded 1921): religious texts, scholarly/academic works, siddurim, and Jewish educational materials. 'Ktav' = 'to write'.","traditionIds":["universal","modern-orthodox"],"languages":["en","he"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"judaica-press","name":"Judaica Press","type":"publisher","url":"https://judaicapress.com","description":"Brooklyn Orthodox publisher (50+ years): Tanakh with classic commentary (the Judaica Books of the Prophets), siddurim, children's books, and Jewish fiction.","traditionIds":["universal","litvish"],"languages":["en","he"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"gefen","name":"Gefen Publishing House","type":"publisher","url":"https://www.gefenpublishing.com","description":"Jerusalem-based English-language publisher (founded 1981) of books of Jewish and Israeli interest; ~40 titles/year. Often co-publishes with OU Press.","traditionIds":["modern-orthodox","universal"],"languages":["en"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"oupress","name":"OU Press","type":"publisher","url":"https://oupress.org","description":"Book-publishing imprint of the Orthodox Union: Jewish thought and prayer, including works of Rabbi Soloveitchik and the Mesorat HaRav series. Often co-published with Koren/Maggid and Gefen.","traditionIds":["modern-orthodox"],"languages":["en","he"],"uiLanguages":["en"],"medium":["print"],"authorityIds":["hershel-schachter"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"soncino","name":"Soncino Press","type":"publisher","url":"https://soncino.com","description":"UK Jewish publisher (named for the 15th-c. Soncino printing family); best known for the Soncino English Talmud and Hebrew Bible translations and commentaries, long used in Orthodox and Conservative settings.","traditionIds":["universal","modern-orthodox"],"languages":["en","he"],"uiLanguages":["en"],"medium":["print"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},

    # X. Kashrus (consumer kosher information)
    {"id":"crc-consumer","name":"cRc Consumer Kosher","type":"kashrus","url":"https://consumer.crckosher.org","description":"Chicago Rabbinical Council's consumer kashrus resource (est. 1932): kosher product lists, liquor/medicine guidance, Pesach guides, kashrus alerts, a hechsher-scanner app, and a published 'Acceptable Kashrus Agencies' list. One of the 'Big Five'.","traditionIds":["universal","litvish"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"ou-kosher","name":"OU Kosher","type":"kashrus","url":"https://oukosher.org","description":"Orthodox Union's kosher certification agency (founded 1923): the most recognized hechsher worldwide (~70% of certified kosher food), certifying ~1,000,000 products in 100+ countries. Consumer halacha, Passover guides, and an app.","traditionIds":["universal","modern-orthodox"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"ok-kosher","name":"OK Kosher Certification","type":"kashrus","url":"https://www.ok.org","description":"Major 'Big Five' kosher agency (Organized Kashrut Laboratories, founded 1935; Brooklyn, Chabad-affiliated leadership): worldwide certification, consumer kosher education, and product search.","traditionIds":["universal","chabad"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"kof-k","name":"Kof-K Kosher Supervision","type":"kashrus","url":"https://www.kof-k.org","description":"Major 'Big Five' kosher agency (Teaneck, NJ, founded 1970): worldwide certification, consumer resources, and kashrus alerts.","traditionIds":["universal","modern-orthodox"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"star-k","name":"Star-K Kosher Certification","type":"kashrus","url":"https://www.star-k.org","description":"Major 'Big Five' kosher agency (Vaad Hakashrus of Baltimore, R. Moshe Heinemann): worldwide certification, extensive consumer kashrus articles, appliance/Shabbat-mode guidance, and Passover lists. Widely trusted by Orthodox Jews.","traditionIds":["universal","litvish"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"klbd","name":"KLBD — Kosher London Beth Din","type":"kashrus","url":"https://www.klbdkosher.org","altUrls":["https://www.kosher.org.uk"],"description":"Kashrut division of the London Beth Din (Court of the Chief Rabbi): Europe's largest kosher agency and a top-five global certifier, recognized by all major kosher organizations. Consumer food guides, restaurant/shop listings, and certification.","traditionIds":["universal","modern-orthodox"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"ako-kosher","name":"AKO — Association of Kashrus Organizations","type":"kashrus","url":"https://www.akokosher.org","description":"Umbrella body of the world's recognized kosher certification agencies: sets shared standards, resolves inter-agency questions, and publishes its member list — a key reference for which hashgachos are mainstream-accepted.","traditionIds":["universal"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"kosherquest","name":"Kosherquest (Kosher Information Bureau)","type":"kashrus","url":"https://kosherquest.org","description":"Consumer kashrus information hub (R. Eidlitz / Kosher Information Bureau, LA): kosher symbol directory by region, product and ingredient guidance, and travel kashrus info.","traditionIds":["universal"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # XII. Russian-language (русскоязычные) resources
    {"id":"ru-chabad","name":"Chabad.org на русском (ru.chabad.org)","type":"general-portal","url":"https://ru.chabad.org","description":"Full Russian-language Chabad portal: Torah study, weekly parsha, Jewish calendar, Ask the Rabbi, and beginner material. The largest Russian-interface Orthodox site.","traditionIds":["chabad","universal"],"languages":["ru"],"uiLanguages":["ru"],"medium":["text","video","audio"],"authorityIds":["menachem-mendel-schneerson"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"toldot","name":"Toldot (Толдот)","type":"general-portal","url":"https://toldot.com","altUrls":["https://toldot.ru"],"description":"Leading Russian-language Orthodox Torah and outreach (kiruv) site: halacha, parsha, Q&A, and Rav Asher Kushnir's audio lectures. Russian-interface, aimed at the FSU diaspora.","traditionIds":["litvish","universal"],"languages":["ru"],"uiLanguages":["ru"],"medium":["text","audio","video"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"jewish-ru","name":"Jewish.ru","type":"general-portal","url":"https://jewish.ru","description":"Global Russian-language Jewish online center (Federation of Jewish Communities / Chabad-affiliated): news, Torah, history, and community content. Russian interface.","traditionIds":["chabad","universal"],"languages":["ru"],"uiLanguages":["ru"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"chassidus-ru","name":"Chassidus.ru (Хасидус по-русски)","type":"text-library","url":"https://chassidus.ru","description":"Russian-language library of Chabad chassidus, Jewish books, holidays, and history. Russian interface.","traditionIds":["chabad"],"languages":["ru"],"uiLanguages":["ru"],"medium":["text"],"access":"free","hasApi":False,"verification":V("not-checked")},

    # XIII. French-language (francophones) resources
    {"id":"torah-box","name":"Torah-Box","type":"general-portal","url":"https://www.torah-box.com","description":"Major French-language Orthodox Torah portal (founded under R. David Abi'hssira and Chief Rabbi Yosef Haim Sitruk): 500+ courses, halacha, news, weekly parsha, ebooks, and an app. The leading francophone Torah resource.","traditionIds":["sephardic","universal"],"languages":["fr"],"uiLanguages":["fr"],"medium":["text","audio","video"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"torah-academy-fr","name":"Torah Academy (torahacademy.fr)","type":"shiur-library","url":"https://www.torahacademy.fr","description":"Online French-language Torah center: series of courses, daily Torah articles, and a halacha Q&A system for the francophone public. French interface.","traditionIds":["universal"],"languages":["fr"],"uiLanguages":["fr"],"medium":["text","audio"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"consistoire","name":"Consistoire de Paris","type":"organization","url":"https://www.consistoire.org","description":"Official French Orthodox communal body (founded 1808 under Napoleon): synagogues, Talmud Torah education, rabbinic services, and the e-Talmud Torah online program. French interface.","traditionIds":["universal","modern-orthodox"],"languages":["fr"],"uiLanguages":["fr"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # XIV. Spanish-language (en español) resources
    {"id":"es-chabad","name":"Chabad.org en Español (es.chabad.org)","type":"general-portal","url":"https://es.chabad.org","description":"Full Spanish-language Chabad portal: Torah, halacha, parsha, daily study, Ask the Rabbi, and beginner material. The largest Spanish-interface Orthodox site.","traditionIds":["chabad","universal"],"languages":["es"],"uiLanguages":["es"],"medium":["text","video","audio"],"authorityIds":["menachem-mendel-schneerson"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"shiurim-app","name":"Shiurim (shiurim.app)","type":"daily-study","url":"https://shiurim.app","description":"Mexico City-based Spanish daily-study project (est. 2017): weekly printable Torah study booklets (Chumash, Rambam and more) for the Spanish-speaking world; 2,000+ readers across 12 countries.","traditionIds":["chabad","universal"],"languages":["es"],"uiLanguages":["es"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"halakha-of-the-day","name":"Halakha of the Day (Rabino Bitton)","type":"halacha","url":"https://halakhaoftheday.org","description":"Daily halacha by R. Yosef Bitton in English and Spanish, with a strong Sephardic focus; one article per day, notable for its section on Sephardic poskim.","traditionIds":["sephardic","sephardic-syrian"],"languages":["es","en"],"uiLanguages":["es","en"],"medium":["text","audio"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"torat-emet-vinas","name":"Centro de Estudios Judíos Torat Emet","type":"organization","url":"https://www.toratemet.org","description":"Spanish-language Sephardic Torah center (R. Rigoberto Manny Viñas): classes, the 'Torá Tropical' publication, and outreach notably serving Anusim / Bnei Anusim (crypto-Jewish heritage) communities.","traditionIds":["sephardic","bnei-anusim","universal"],"languages":["es"],"uiLanguages":["es"],"medium":["text","video"],"access":"free","hasApi":False,"verification":V("not-checked","","Center and Rabbi Viñas well-documented; exact current domain unverified.")},
    {"id":"shavei-israel","name":"Shavei Israel","type":"organization","url":"https://www.shavei.org","description":"Jerusalem-based organization (founded 2002, Michael Freund) reconnecting 'lost' and hidden Jewish communities with the Jewish people. Has dedicated Bnei Anusim and Bnei Menashe programs, the Spanish-language Machon Miriam return/conversion institute, and multilingual educational material.","traditionIds":["bnei-anusim","bnei-menashe","sephardic","universal"],"languages":["en","es","pt","he"],"uiLanguages":["en","es"],"medium":["text","video"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"degel-menashe","name":"Degel Menashe","type":"organization","url":"https://www.degelmenashe.org","description":"Israeli NGO (founded 2019, grew out of a Bnei Menashe oral-history project) supporting the Bnei Menashe in Israel and India: integration, education, heritage preservation, and advocacy for aliyah. Operates independently of Shavei Israel.","traditionIds":["bnei-menashe"],"languages":["en","he"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # XV. Portuguese-language (em português) resources
    {"id":"pt-chabad","name":"Chabad.org em Português (pt.chabad.org)","type":"general-portal","url":"https://pt.chabad.org","description":"Full Portuguese-language Chabad portal: Torah, halacha, parsha, daily study, and Ask the Rabbi. The largest Portuguese-interface Orthodox site, serving Brazil and Portugal.","traditionIds":["chabad","universal"],"languages":["pt"],"uiLanguages":["pt"],"medium":["text","video","audio"],"authorityIds":["menachem-mendel-schneerson"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"beit-chabad-brasil","name":"Beit Chabad do Brasil","type":"organization","url":"https://www.beitchabad.org.br","description":"Brazilian Chabad organization's own Portuguese-language site (São Paulo): Torah study, parsha, halacha, Ask the Rabbi, and community resources.","traditionIds":["chabad"],"languages":["pt"],"uiLanguages":["pt"],"medium":["text","video"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"chabad-portugal","name":"Chabad Portugal","type":"institution","url":"https://www.chabadportugal.com","description":"Chabad of Portugal (Cascais): community center with the Aaron & Joshua Nasser library, which holds Torah works by Portuguese Jewish scholars and early (15th-c.) Lisbon-printed Hebrew books.","traditionIds":["chabad","universal"],"languages":["pt","en"],"uiLanguages":["pt","en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("not-checked")},

    # XVI. Interactive learning platforms & reference works
    {"id":"mercava","name":"Mercava","type":"app","url":"https://www.themercava.com/app/","description":"Nonprofit Jewish ed-tech platform ('the OS of Jewish education'): interactive sefarim (Tanach, Mishnah, Talmud, Rambam, Shulchan Aruch), learning/teaching apps, chavruta tools, and a Daf Yomi app, on web and mobile. Originated with backing from Brooklyn's Syrian Jewish community.","traditionIds":["universal","modern-orthodox","sephardic-syrian"],"languages":["en","he","arc"],"uiLanguages":["en"],"medium":["text"],"access":"freemium","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"aspaklaria","name":"Aspaklaria (אספקלריא)","type":"text-library","url":"https://www.aspaklaria.info","description":"Hebrew encyclopedia/compendium of Jewish thought (ed. Shmuel Avraham Adler): each concept entry gathers full source texts from Tanakh, rabbinic literature, medieval philosophy, Zohar, Maharal, Hasidut, Musar, and Rav Kook. Hebrew-only interface.","traditionIds":["universal"],"languages":["he","arc"],"uiLanguages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # XVII. AI & computational Torah tools (newer layer, 2022-2026)
    {"id":"ohrbit","name":"OHRBIT","type":"ai-tool","url":"https://www.ou.org/news/the-orthodox-union-launches-revolutionary-ai-powered-torah-app/","description":"The Orthodox Union's first AI-powered Torah app (launched Feb 2026): personalizes study by interest and level across text, audio and video, with scheduling and gamified streaks. Draws on OU content plus partners including The Rabbi Sacks Legacy and OpenDor Media; includes mental-health and safe-AI guardrails.","traditionIds":["modern-orthodox","universal"],"languages":["en"],"uiLanguages":["en"],"medium":["text","audio","video"],"authorityIds":["jonathan-sacks"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"Launched Feb 2026; link points to the OU announcement — replace with the app's own URL/store listing when confirmed."),"flags":["New (2026) — app URL not yet pinned; announcement page used."]},
    {"id":"dicta","name":"Dicta — Israel Center for Text Analysis","type":"ai-tool","url":"https://dicta.org.il/?lang=en","description":"Israeli nonprofit (founded by Prof. Moshe Koppel) applying machine learning and NLP to Hebrew and rabbinic texts. Free tools: automatic nikud/vocalization, abbreviation expansion, OCR for Rashi-script and old printings (Dicta Maivin), scriptural allusion finder, synopsis/recension alignment, and advanced Bible/Talmud search. Also releases open models (BEREL, AlephBertGimmel).","traditionIds":["universal"],"languages":["he","arc","en"],"uiLanguages":["he","en"],"medium":["text"],"access":"free","hasApi":True,"verification":V("verified-live",LIVE)},
    {"id":"sefaria-ai","name":"Sefaria — AI & Developer Tools","type":"ai-tool","url":"https://www.sefaria.org/ai","description":"Sefaria's AI program and developer surface: AI-assisted translations (first release, the Kli Yakar commentary, early 2026, human-edited over six months), AI-curated topic pages, the Linker API, and an MCP server that lets AI assistants query Sefaria's library directly instead of recalling texts from training data.","traditionIds":["universal"],"languages":["en","he","arc"],"uiLanguages":["en"],"medium":["text"],"access":"api-open","hasApi":True,"verification":V("verified-live",LIVE)},
    {"id":"torahapp","name":"TorahApp","type":"app","url":"https://torahapp.org","description":"Free all-in-one Orthodox Torah study app: opens a sefer and surfaces all related shiurim, combining Sefaria's open texts with recorded shiur libraries. Daily learning calendars, tikkun mode for practicing leining, multi-tab study, and offline access. Developed with rabbinic guidance.","traditionIds":["universal","modern-orthodox"],"languages":["en","he"],"uiLanguages":["en"],"medium":["text","audio"],"access":"free","hasApi":False,"verification":V("not-checked","","App well-documented in Jewish press; exact current domain unverified.")},

    # XI. Counter-missionary / counter-cult education
    {"id":"outreach-judaism","name":"Outreach Judaism","type":"counter-missionary","url":"https://outreachjudaism.org","description":"International counter-missionary organization (R. Tovia Singer) responding to Christian missionaries and cults targeting Jews; the 'Let's Get Biblical' audio series, lectures, and the Tovia Singer Show.","traditionIds":["universal"],"languages":["en"],"uiLanguages":["en"],"medium":["text","audio","video"],"authorityIds":["tovia-singer"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"jews-for-judaism","name":"Jews for Judaism","type":"counter-missionary","url":"https://jewsforjudaism.org","description":"International counter-missionary and counter-cult organization (founded 1985, R. Bentzion Kravitz); education, counseling, and the free multilingual 'Jewish Response to Missionaries' handbook. Serves all Jewish denominations.","traditionIds":["universal"],"languages":["en"],"uiLanguages":["en"],"medium":["text","audio","video"],"authorityIds":["bentzion-kravitz"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},

    # V. Sephardic / Mizrahi
    {"id":"halachayomit","name":"HalachaYomit","type":"halacha","url":"https://halachayomit.co.il/en/","description":"Daily halacha based on Rav Ovadia's rulings; most structured daily-delivery resource in this stream.","traditionIds":["sephardic-ovadia"],"languages":["he","en"],"medium":["text"],"textIds":["yalkut-yosef"],"authorityIds":["ovadia-yosef"],"access":"free-registration","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"dailyhalacha","name":"DailyHalacha.com","type":"halacha","url":"https://www.dailyhalacha.com","description":"R. Eli Mansour's daily halacha, weekly parasha, and large searchable audio archive; richest English Sephardic resource (Syrian custom).","traditionIds":["sephardic-syrian","sephardic"],"languages":["en"],"medium":["text","audio"],"authorityIds":["eli-mansour"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"darke-abotenou-site","name":"Darké Abotenou","type":"halacha","url":"https://www.darkeabotenou.com","description":"Laws and customs of the Jews of Morocco in English/French; daily halacha to 9,000+ subscribers plus a large YouTube archive of Moroccan piyutim and tefilot.","traditionIds":["sephardic-moroccan"],"languages":["en","fr","he"],"uiLanguages":["en"],"medium":["text","video"],"textIds":["darke-abotenou"],"authorityIds":["mordechai-lebhar"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"moroccan-halacha","name":"Magen Avot / Machon Magen Avot","type":"halacha","url":"https://www.moroccanhalacha.com","description":"R. Mordechai Lebhar's daily Moroccan halacha, audio/video shiurim, and publishing house for Moroccan/Sephardic manuscripts.","traditionIds":["sephardic-moroccan"],"languages":["en","he"],"uiLanguages":["en"],"medium":["text","audio","video"],"textIds":["magen-avot"],"authorityIds":["mordechai-lebhar","shalom-messas"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"midrash-ben-ish-hai","name":"Midrash Ben Ish Hai / A Torah Minute","type":"halacha","url":"https://www.midrash.org","altUrls":["https://www.atorahminute.com"],"description":"R. Yaakov Menashe's English Baghdadi/Sephardic halacha and Ben Ish Chai teachings; serves the worldwide Baghdadi diaspora (incl. Indian communities). Includes a women's section.","traditionIds":["sephardic-iraqi","sephardic"],"languages":["en"],"uiLanguages":["en"],"medium":["text","audio"],"textIds":["ben-ish-chai"],"authorityIds":["yaakov-menashe","yosef-chaim-baghdad"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"hevrat-pinto","name":"Hevrat Pinto","type":"organization","url":"https://www.hevratpinto.org","description":"Pinto-dynasty Sephardic (Moroccan-rooted) organization; multilingual Torah, parasha, and tzadikim content including Ben Ish Chai material.","traditionIds":["sephardic-moroccan","sephardic"],"languages":["en","fr","he"],"uiLanguages":["en","fr","he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"sephardi-toolkit","name":"Sephardi & Mizrahi Education Toolkit","type":"general-portal","url":"https://www.sepharditoolkit.org","description":"Educational resource cataloging Sephardi/Mizrahi halacha, minhagim, liturgy, and sources across communities (Iraqi, Moroccan, Yemenite, etc.).","traditionIds":["sephardic","sephardic-iraqi","sephardic-moroccan"],"languages":["en"],"uiLanguages":["en"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"sephardic-u","name":"Sephardic U","type":"general-portal","url":"https://www.sephardicu.com","description":"Global Sephardic heritage, history, and halacha hub; spans the multiple rites rather than just the Rav Ovadia mainstream.","traditionIds":["sephardic"],"languages":["en"],"medium":["text","video"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"porat-yosef","name":"Yeshivat Porat Yosef","type":"institution","url":"https://www.poratyosef.org.il","description":"Premier Sephardic yeshiva in Israel (founded 1923); institutional cradle of much of the modern Sephardic rabbinate. Primarily Hebrew.","traditionIds":["sephardic","sephardic-ovadia"],"languages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("unconfirmed",LIVE,"Yeshiva confirmed to exist; no official poratyosef.org.il homepage found in search. Verify or remove URL."),"flags":["URL unconfirmed — check before publishing."]},
    {"id":"ateret4u","name":"Yalkut Yosef (official site)","type":"text-library","url":"https://yalkutyosef.co.il","description":"Official Yalkut Yosef site (R. Yitzchak Yosef): Hebrew text plus a daily-halacha feature. Replaces the previously-listed ateret4u.com.","traditionIds":["sephardic-ovadia"],"languages":["he"],"uiLanguages":["he"],"medium":["text"],"textIds":["yalkut-yosef"],"authorityIds":["yitzchak-yosef"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"Confirmed at yalkutyosef.co.il; original ateret4u.com did not resolve.")},

    # VI. Beta Israel
    {"id":"orit-guardians","name":"Orit Guardians","type":"archive","url":None,"description":"Tel Aviv University program documenting and digitizing Beta Israel manuscripts and the Kessim's oral tradition (with the National Library of Israel).","traditionIds":["beta-israel"],"languages":["gez","he"],"medium":["text"],"textIds":["orit"],"access":"free","hasApi":False,"verification":V("not-checked"),"flags":["Heritage/academic project, not a study platform.","Engage community before publishing Haymanot content."]},
    {"id":"nli","name":"National Library of Israel","type":"archive","url":"https://www.nli.org.il/en","description":"Manuscript holdings and a growing digital archive of Beta Israel texts, among broad Judaica collections.","traditionIds":["beta-israel","universal"],"languages":["he","en"],"medium":["text"],"textIds":["orit"],"access":"free","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"anu-museum","name":"ANU — Museum of the Jewish People","type":"archive","url":"https://www.anumuseum.org.il/en/","description":"Exhibitions and educational material on Ethiopian Jewish (and broader) heritage.","traditionIds":["beta-israel","universal"],"languages":["en","he"],"uiLanguages":["en","he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("not-checked")},

    # VII. Hebrew-UI-only resources (interface requires Hebrew to navigate)
    {"id":"hebwikisource","name":"HebrewWikisource (ויקיטקסט)","type":"text-library","url":"https://he.wikisource.org","description":"Crowd-sourced open library of Jewish and Hebrew texts; navigation and search are Hebrew-only.","traditionIds":["universal"],"languages":["he","arc"],"uiLanguages":["he"],"medium":["text"],"access":"free","hasApi":True,"verification":V("verified-live",LIVE)},
    {"id":"mechon-mamre","name":"Mechon Mamre","type":"text-library","url":"https://www.mechon-mamre.org","description":"Full Tanakh, Mishnah, Talmud, and Rambam's Mishneh Torah in Hebrew (with English in places). Run by Baladi Yemenite Rambamist scholars, disciples of R. Yosef Qafih.","traditionIds":["universal","sephardic-yemenite"],"languages":["he","arc","en"],"uiLanguages":["he","en"],"medium":["text"],"authorityIds":["yosef-qafih"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"hebrewbooks-search","name":"Otzar HaChochma","type":"text-library","url":"https://www.otzar.org","altUrls":["https://tablet.otzar.org"],"description":"World's largest digital library of scanned sefarim (~156,000 titles); Hebrew-only interface, web + tablet access, aimed at scholars.","traditionIds":["universal","litvish"],"languages":["he","arc"],"uiLanguages":["he"],"medium":["text"],"access":"paid","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"daf-yomi-portal","name":"Yeshiva.org.il (ישיבה)","type":"shiur-library","url":"https://www.yeshiva.org.il","description":"Large Religious-Zionist Hebrew shiur and Q&A portal (Beit El Yeshiva). Hebrew interface; its English arm split off as yeshiva.co in 2013.","traditionIds":["modern-orthodox"],"languages":["he"],"uiLanguages":["he"],"medium":["text","audio","video"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"kipa","name":"Moreshet (מורשת)","type":"general-portal","url":"https://www.moreshet.co.il","description":"Hebrew Religious-Zionist portal with halacha Q&A and parsha content; Hebrew-only interface.","traditionIds":["modern-orthodox"],"languages":["he"],"uiLanguages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"hebrew-dirshu","name":"Dirshu (Hebrew portal)","type":"organization","url":"https://www.dirshu.co.il","description":"Hebrew-interface home of Dirshu's Israeli programs and registration, distinct from the English .com.","traditionIds":["litvish"],"languages":["he"],"uiLanguages":["he"],"medium":["text"],"textIds":["mishnah-berurah"],"access":"freemium","hasApi":False,"verification":V("verified-live","2026-06-02")},
    {"id":"hidabroot-he","name":"Hidabroot (הידברות)","type":"general-portal","url":"https://www.hidabroot.org","description":"Major Hebrew Haredi outreach/media portal with extensive shiurim; Hebrew-first interface (some translated sections exist).","traditionIds":["haredi","sephardic-ovadia"],"languages":["he"],"uiLanguages":["he"],"medium":["text","video","audio"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"kol-halashon","name":"Kol Halashon (קול הלשון)","type":"shiur-library","url":"https://www.kolhalashon.com","description":"Vast Haredi audio/video shiur library and app, organized by rabbi, topic, and audience; available even under the strictest kosher internet filters. Hebrew-first (also multi-language).","traditionIds":["haredi","litvish","hasidic"],"languages":["he","yi","en"],"uiLanguages":["he"],"medium":["audio","video","text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"kol-hadaf","name":"Kol HaDaf (קול הדף)","type":"daily-study","url":"https://www.kolhadaf.com","description":"Haredi organization distributing Daf Yomi and other Torah shiurim by phone and audio (Hebrew/Yiddish); Bavli daf from R. Michel Zilber, Yerushalmi from R. Yisrael Dandrovitz.","traditionIds":["haredi","litvish"],"languages":["he","yi"],"uiLanguages":["he"],"medium":["audio","phone"],"access":"free","hasApi":False,"verification":V("not-checked","","Organization well-documented; exact current domain unverified.")},
    {"id":"halacha-brura","name":"Machon Halacha Brura (מכון הלכה ברורה)","type":"text-library","url":"https://www.halachabrura.org","description":"Hebrew virtual library of responsa and halachic works, tied to R. David Yosef's Halacha Brura / Halichot Olam project; Hebrew-only interface.","traditionIds":["sephardic-ovadia"],"languages":["he"],"uiLanguages":["he"],"medium":["text"],"textIds":["yalkut-yosef"],"authorityIds":["david-yosef"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"srugim","name":"Srugim (סרוגים)","type":"general-portal","url":"https://www.srugim.co.il","description":"Hebrew Religious-Zionist news and Torah portal with a 'Ask the Rabbi' responsa archive; Hebrew-only interface.","traditionIds":["modern-orthodox"],"languages":["he"],"uiLanguages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE)},
    {"id":"toratemet","name":"Torat Emet (תורת אמת)","type":"text-library","url":"https://www.toratemetfreeware.com","description":"Free Hebrew Torah-text search software and online library (Tanakh, Talmud, halacha, responsa); Hebrew-only interface.","traditionIds":["universal","litvish"],"languages":["he","arc"],"uiLanguages":["he"],"medium":["text"],"access":"free","hasApi":False,"verification":V("not-checked")},

    # VIII. Yiddish-UI-only resources (interface in Yiddish; serves the Yiddish-first dynasties)
    {"id":"kave-shtiebel","name":"Kave Shtiebel (קאווע שטיבל)","type":"general-portal","url":"https://www.kaveshtiebel.com","description":"Hasidic Yiddish-language discussion forum (2012-2024). A rare Yiddish text-web space, but a general forum rather than a study resource. Announced closure in Aug 2024; successor forum is Kraiml (login required).","traditionIds":["hasidic","satmar"],"languages":["yi"],"uiLanguages":["yi"],"medium":["text"],"access":"free","hasApi":False,"verification":V("dead",LIVE,"Announced closure Aug 2024; blocked by some kosher filters. Successor: Kraiml."),"flags":["Closing/closed as of 2024 — likely remove or replace with Kraiml.","A discussion forum, not a study platform."]},
    {"id":"yiddish-shiurim","name":"Yiddish Shiurim hotline directories","type":"shiur-library","url":None,"phone":"varies","description":"Community Yiddish shiur hotlines (e.g. dial-in Torah lines run within Satmar/Belz/Skver). Audio-first, Yiddish-only; no unified web interface.","traditionIds":["satmar","belz","skver","hasidic"],"languages":["yi"],"uiLanguages":["yi"],"medium":["audio","phone"],"access":"free","hasApi":False,"verification":V("not-checked"),"flags":["Aggregated category, not a single site; numbers circulate within communities."]},
    {"id":"khol-hamoyed","name":"Yiddish24 — written section (וואָרט)","type":"general-portal","url":"https://www.yiddish24.com","description":"The text/written Yiddish content arm associated with the Yiddish24 network; Yiddish-only interface.","traditionIds":["satmar","belz","hasidic"],"languages":["yi"],"uiLanguages":["yi"],"medium":["text"],"access":"free","hasApi":False,"verification":V("not-checked"),"flags":["Closely tied to the yiddish24 hotline entry."]},

    # IX. Ladino-UI resources (Judeo-Spanish interface; largely cultural/heritage, not study)
    {"id":"autoridad-nasionala-ladino","name":"Autoridad Nasionala del Ladino","type":"organization","url":"https://www.ladino-authority.com","description":"Israel's national authority for Ladino and its culture; Judeo-Spanish interface and publications. Heritage/cultural rather than a halacha study platform.","traditionIds":["sephardic-spanish-portuguese","sephardic"],"languages":["lad"],"uiLanguages":["lad"],"medium":["text"],"access":"free","hasApi":False,"verification":V("unconfirmed",LIVE,"Organization real (est. 1997); 2018 successor is the Akademia Nasionala del Ladino. Exact current URL unverified."),"flags":["Cultural/linguistic preservation, not a Torah-study resource.","Ladino is critically endangered; web presence is minimal.","Check whether to point to Akademia Nasionala del Ladino instead."]},
    {"id":"ladinokomunita","name":"Ladinokomunita","type":"general-portal","url":"https://ladinokomunita.groups.io/g/main","description":"Long-running global email correspondence circle written entirely in Ladino (~hundreds of members). A language community, not a study platform; some traditional/liturgical discussion.","traditionIds":["sephardic-spanish-portuguese","sephardic"],"languages":["lad"],"uiLanguages":["lad"],"medium":["text"],"access":"free","hasApi":False,"verification":V("verified-live",LIVE,"Hosted as a groups.io mailing list, not a standalone .org site."),"flags":["Primarily a language community, not a study platform."]},
]

# ─── Backfill uiLanguages where not explicitly set ───────────────────────────
# Resources known to have a Hebrew-ONLY navigation interface:
HEBREW_UI_ONLY = {"daat", "ateret4u", "porat-yosef"}
# Resources known to offer an English interface even if content is multilingual:
HAS_EN_UI = {"sefaria","hebrewbooks","alhatorah","torahanytime","alltorah","chabad-org",
             "jnet","kabbalahonline","therebbe","sie","breslovtorah","breslov-research",
             "nanach","sfasemes-org","torah-org-sfasemes","torahjews-org","worldofbelz",
             "torahdownloads","heichal-hanegina","bmg","torah-vodaas","chaim-berlin",
             "mir-brooklyn","agudah","dirshu","artscroll","alldaf","mdy","steinsaltz",
             "hadran","koveah","yutorah","ou-torah","vbm","torahweb","mizrachi","rca",
             "webyeshiva","alephbeta","aish","koren","halachayomit","dailyhalacha",
             "sephardic-u","nli"}
# Audio/phone resources where 'navigation' is spoken Yiddish, not a text UI:
YIDDISH_AUDIO_UI = {"yiddish24"}

for r in resources:
    if "uiLanguages" in r:
        continue  # explicitly set on the new entries
    rid = r["id"]
    if rid in HEBREW_UI_ONLY:
        r["uiLanguages"] = ["he"]
    elif rid in YIDDISH_AUDIO_UI:
        r["uiLanguages"] = ["yi"]
    elif rid in HAS_EN_UI:
        r["uiLanguages"] = ["en"]
    else:
        # conservative default: mirror content languages
        r["uiLanguages"] = list(r.get("languages", []))


dataset = {
    "meta": {
        "version": "1.1.0",
        "generatedAt": "2026-06-03",
        "source": "Built from the full 'Orthodox Jewish Study Resources' reference document. v1.1 adds uiLanguages (interface/navigation language) and Hebrew-UI-only sources.",
        "disclaimer": "Leadership and URL details drift over time; entries flagged for human verification should be confirmed before publishing."
    },
    "traditions": traditions,
    "authorities": authorities,
    "texts": texts,
    "resources": resources,
}

with open("data/full-data.json","w",encoding="utf-8") as f:
    json.dump(dataset, f, ensure_ascii=False, indent=2)

print(f"traditions={len(traditions)} resources={len(resources)} texts={len(texts)} authorities={len(authorities)}")
